apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hive.fullname" . }}
  labels:
    app: {{ template "hive.name" . }}
    chart: {{ template "hive.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "hive.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "hive.name" . }}
        release: {{ .Release.Name }}
    spec:
{{- if .Values.volumes }}
      volumes:
{{ include .Values.volumes.volumesTemplate . | indent 8 }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "-x", "{{ .Values.image.command }}"]
          ports:
            - name: server
              containerPort: {{ .Values.server.containerPort }}
              protocol: TCP
            - name: ui
              containerPort: {{ .Values.ui.containerPort }}
              protocol: TCP
            - name: metastore
              containerPort: {{ .Values.metastore.containerPort }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.metastore.containerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.metastore.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          env:
            - name: HIVE_CONF_DIR
              value: {{ .Values.configPath }}
            - name: HIVE_DB_TYPE
              value: {{ .Values.databaseType }}
{{- if .Values.environment}}
{{ include .Values.environment.template . | indent 12 }}
{{- end }}
{{- if .Values.volumes }}
          volumeMounts:
{{ include .Values.volumes.volumeMountsTemplate . | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
