{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hive.fullname" . }}-metastore-auth
  labels:
    app: {{ template "hive.name" . }}
    chart: {{ template "hive.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  metastorePassword: {{ .Values.metastore.database.password | b64enc | quote }}
  metastoreAdminPassword: {{ .Values.createHiveUserMariaDbImage.password | b64enc | quote }}
{{- end -}}
