apiVersion: v1
kind: Service
metadata:
  name: {{ template "hive.fullname" . }}
  labels:
    app: {{ template "hive.name" . }}
    chart: {{ template "hive.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.hive.server.servicePort }}
      targetPort: {{ .Values.hive.server.containerPort }}
      protocol: TCP
      name: server
    - port: {{ .Values.hive.ui.servicePort }}
      targetPort: {{ .Values.hive.ui.containerPort }}
      protocol: TCP
      name: ui
    - port: {{ .Values.hive.metastore.servicePort }}
      targetPort: {{ .Values.hive.metastore.containerPort }}
      protocol: TCP
      name: metastore
  selector:
    app: {{ template "hive.name" . }}
    release: {{ .Release.Name }}
