apiVersion: v1
kind: Service
metadata:
  name: {{ template "hive.fullname" . }}
  labels:
    app: {{ template "hive.name" . }}
    chart: {{ template "hive.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.server.servicePort }}
      targetPort: {{ .Values.server.containerPort }}
      protocol: TCP
      name: server
    - port: {{ .Values.webUI.servicePort }}
      targetPort: {{ .Values.webUI.containerPort }}
      protocol: TCP
      name: webUI
  selector:
    app: {{ template "hive.name" . }}
    release: {{ .Release.Name }}
