apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-v3io-config
  labels:
    app: {{ template "hive.name" . }}
    chart: {{ template "hive.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ include "v3io-configs.java.configMap" . | indent 2 }}

  v3io-hive.sh: |
    #!/usr/bin/env bash
    set -e

    echo alias ll=\"ls -lah --color\" >> ~/.bash_aliases

{{ include "v3io-configs.script.lookupService" . | indent 4 }}

    V3IO_HIVE_CONFIG={{ .Values.configPath }}
    mkdir -p $V3IO_HIVE_CONFIG

    cp -r $HIVE_HOME/conf/* $V3IO_HIVE_CONFIG/
    cp {{ .Values.global.v3io.configMountPath }}/hive-site.xml $V3IO_HIVE_CONFIG/

    sed -i "s/HIVE_SERVICE_HOST/$HIVE_SERVICE_HOST/g" $V3IO_HIVE_CONFIG/hive-site.xml

    # Initialize Hive metastore database
    # Check if schema does not exists or invalid, then try to initialize Hive metastore database schema
    set +e
    $HIVE_HOME/bin/schematool -dbType $HIVE_DB_TYPE -validate
    set -e
    RC=$?
    
    if [ $RC != 0 ]; then
      echo "Hive schema didn't pass validation. RC=$RC"
      echo "Initializing Hive metastore schema..."
      $HIVE_HOME/bin/schematool -initSchema -dbType $HIVE_DB_TYPE
    else
      echo "Hive metastore schema already exists. Details:"
      $HIVE_HOME/bin/schematool -dbType $HIVE_DB_TYPE -info
    fi

    echo Starting hive metastore service....
    $HIVE_HOME/bin/hive --service metastore

  hive-site.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://{{ .Values.postgres.hostname }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}</value>
      </property>

      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>

      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>{{ .Values.postgres.username }}</value>
      </property>

      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>{{ .Values.postgres.password }}</value>
      </property>

      <property>
        <name>hive.metastore.uris</name>
        <value>thrift://HIVE_SERVICE_HOST:9083</value>
        <description>IP address (or fully-qualified domain name) and port of the metastore host</description>
      </property>

      <property>
        <name>hive.metastore.schema.verification</name>
        <value>true</value>
      </property>
    </configuration>
