apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "v3io-framesd.name" . }}
    chart: {{ template "v3io-framesd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if or .Values.service.httpNodePort .Values.service.grpcNodePort }}
  type: NodePort
{{- end }}
  ports:
    - port: {{ .Values.service.http }}
      targetPort: http
      protocol: TCP
      name: http
{{- if .Values.service.httpNodePort }}
      nodePort: {{ .Values.service.httpNodePort }}
{{- end }}
    - port: {{ .Values.service.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
{{- if .Values.service.grpcNodePort }}
      nodePort: {{ .Values.service.grpcNodePort }}
{{- end }}
  selector:
    app: {{ template "v3io-framesd.name" . }}
    release: {{ .Release.Name }}
