apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgres.fullname" . }}
  labels:
    app: {{ template "postgres.name" . }}
    chart: {{ template "postgres.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.postgres.servicePort }}
      targetPort: {{ .Values.postgres.containerPort }}
      protocol: TCP
      name: postgres
  selector:
    app: {{ template "postgres.name" . }}
    release: {{ .Release.Name }}
