apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-v3io-config
  labels:
    app: {{ template "postgres.name" . }}
    chart: {{ template "postgres.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ include "v3io-configs.java.configMap" . | indent 2 }}

  v3io-postgres.sh: |
    #!/usr/bin/env bash
    set -e

{{ include "v3io-configs.script.lookupService" . | indent 4 }}

    echo alias ll=\"ls -lah --color\" >> ~/.bashrc
    echo "echo ''" >> ~/.bashrc

    /usr/local/bin/startup.sh
