apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-v3io-fuse
  labels:
    app: {{ template "postgres.name" . }}
    chart: {{ template "postgres.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: v3io/fuse
data:
{{ include "v3io-configs.fuse.secret" . | indent 2 }}
