apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mysql.fullname" . }}
  labels:
    app: {{ template "mysql.name" . }}
    chart: {{ template "mysql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "mysql.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "mysql.name" . }}
        release: {{ .Release.Name }}
    spec:
{{- if .Values.mysql.volumes }}
      volumes:
{{ include .Values.mysql.volumes.volumesTemplate . | indent 8 }}
{{- else }}
      volumes:
{{ include .Values.volumes.volumesTemplate . | indent 8 }}
{{- end }}
{{- if .Values.config.hostname }}
      hostname: {{ .Values.config.hostname }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}-mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "-x", "{{ .Values.image.command }}"]
          ports:
            - name: mysql
              containerPort: {{ .Values.mysql.containerPort }}
              protocol: TCP
{{- if .Values.mysql.environment }}
          env:
{{ include .Values.mysql.environment.template . | indent 12 }}
{{- end }}
{{- if .Values.mysql.volumes }}
          volumeMounts:
{{ include .Values.mysql.volumes.volumeMountsTemplate . | indent 12 }}
{{- else }}
          volumeMounts:
{{ include .Values.volumes.volumeMountsTemplate . | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
