apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-v3io-config
  labels:
    app: {{ template "mysql.name" . }}
    chart: {{ template "mysql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  v3io-mysql.sh: |
    #!/usr/bin/env bash
    set -ex

    echo "Current User:"
    whoami

    sleep 30d

    if [ ! -f ~/.bashrc ]; then
      touch ~/.bashrc
    fi

    echo alias ll=\"ls -lah --color\" >> ~/.bashrc

    # Debug
    # sleep 30d

    mysqld
