apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-v3io-auth
  labels:
    app: {{ template "mysql.name" . }}
    chart: {{ template "mysql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ include "v3io-configs.java.secret" . | indent 2 }}
