# Default values for tenant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scaler:
  image:
    repository: iguaziodocker/autoscaler
    tag: 0.1.1
    pullPolicy: IfNotPresent
    command: autoscaler

    # args
    scaleInterval: 1m
    scaleWindow: 10m
    metricsPollInterval: 10s
    metricName: num_of_requests
    metricsGroupKind: Deployment
    scaleThreshold: 0

general:
  image:
    pathMount: /home/app_resourcescaler

dlx:
  image:
    repository: iguaziodocker/dlx
    tag: 0.1.1
    pullPolicy: IfNotPresent
    command: dlx

    # args
    targetNameHeader: X-App-Target
    targetPathHeader: ""
    targetPort: 8080
    listenAddress: :8080


rbac:

  # If true, creates the necessary roles, role bindings and service accounts
  create: true

  # serviceAccountName: service-account-name

nodeSelector: {}

tolerations: []

affinity: {}
