{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "scaler.serviceAccountName" . }}
  labels:
    app: {{ template "scaler.name" . }}
    release: {{ .Release.Name }}
{{- end }}
