apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mariadb.fullname" . }}
  labels:
    app: {{ template "mariadb.name" . }}
    chart: {{ template "mariadb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:

  health_check.sh: |
    mysqladmin --protocol=TCP -uroot -p$MYSQL_ROOT_PASSWORD status

  init-v3io-mariadb.sh: |
    #!/usr/bin/env bash
    set -e

    echo "Current user -> $(whoami)"
    LOCK_FILE=/var/lib/mysql/.init-complete
    if [ -f $LOCK_FILE ]
    then
      echo "MariaDB has already been initialized. Skipping..."
    else
      echo "Initializing MariaDB..."

      mysql_install_db --user=mysql --basedir=/usr --datadir=/tmp/mysql
      # and then copy the init files into real working directory (on Fuse mount)
      cp -R /tmp/mysql /var/lib/

      touch $LOCK_FILE
    fi

  v3io-mariadb.sh: |
    #!/usr/bin/env bash
    set -e

    echo "Current user -> $(whoami)"

    LOCK_FILE=/var/lib/mysql/.allow-remote-access-complete
    if [ ! -f $LOCK_FILE ]
    then
      MYSQL_CONFIG=/etc/mysql/my.cnf
      INIT_SCRIPT="{{ .Values.configMountPath }}/init-scripts/enable-root-remote-access.sql"

      # Call init script on startup
      echo "Adding $INIT_SCRIPT to $MYSQL_CONFIG ..."
      echo "" >> $MYSQL_CONFIG
      echo "[mysqld]" >> $MYSQL_CONFIG
      echo "init-file=$INIT_SCRIPT" >> $MYSQL_CONFIG

      touch $LOCK_FILE
    fi

    echo "Starting MariaDB..."
    # start the database server daemon
    mysqld
