apiVersion: v1
kind: Service
metadata:
  name: {{ template "mariadb.fullname" . }}
  labels:
    app: {{ template "mariadb.name" . }}
    chart: {{ template "mariadb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: mariadb
      port: {{ .Values.server.port }}
      targetPort: mariadb
      protocol: TCP
  selector:
    app: {{ template "mariadb.name" . }}
    release: {{ .Release.Name }}
