apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mariadb.fullname" . }}
  labels:
    app: {{ template "mariadb.name" . }}
    chart: {{ template "mariadb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "mariadb.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "mariadb.name" . }}
        release: {{ .Release.Name }}
    spec:
{{- if .Values.volumes }}
      volumes:
{{ include .Values.volumes.volumesTemplate . | indent 8 }}
        # Add mysql data fuse mount
        - name: mysql-fuse
          flexVolume:
            driver: "v3io/fuse"
            secretRef:
              name: {{ .Release.Name }}-v3io-fuse
            options:
              container: bigdata
              subPath: /mysql
{{- end }}
      containers:
        - name: {{ .Chart.Name }}-mariadb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "-x", "{{ .Values.image.command }}"]
          ports:
            - name: mysql
              containerPort: {{ .Values.server.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - {{ .Values.global.v3io.configMountPath }}/health_check.sh
              initialDelaySeconds: {{ .Values.server.readinessProbe.initialDelaySeconds }}
              periodSeconds: {{ .Values.server.readinessProbe.periodSeconds }}
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - {{ .Values.global.v3io.configMountPath }}/health_check.sh
              initialDelaySeconds: 5
              periodSeconds: 1
{{- if .Values.environment }}
          env:
{{ include .Values.environment.template . | indent 12 }}
{{- end }}
{{- if .Values.volumes }}
          volumeMounts:
{{ include .Values.volumes.volumeMountsTemplate . | indent 12 }}
            - name: mysql-fuse
              mountPath: "/var/lib/mysql"
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
