{{- if gt (int .Values.server.workers) 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "presto.worker" . }}
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: worker
data:
  node.properties: |
    node.environment={{ .Values.server.node.environment }}
    node.data-dir={{ .Values.server.node.dataDir }}

  jvm.config: |
    -server
    -Xmx{{ .Values.server.jvm.maxHeapSize }}
    -XX:+{{ .Values.server.jvm.gcMethod.type }}
    -XX:G1HeapRegionSize={{ .Values.server.jvm.gcMethod.g1.heapRegionSize }}
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError

  config.properties: |
    coordinator=false
    http-server.http.port={{ .Values.server.config.http.port }}
{{- if .Values.server.config.https }}
    http-server.https.enabled=true
    http-server.https.port={{ .Values.server.config.https.port }}
    http-server.https.keystore.path={{ .Values.server.config.https.keystore }}
    http-server.https.keystore.key={{ .Values.server.config.https.passphrase }}
    http-server.authentication.type=PASSWORD
{{- end }}
    query.max-memory={{ .Values.server.config.query.maxMemory }}
    query.max-memory-per-node={{ .Values.server.config.query.maxMemoryPerNode }}
    discovery.uri=http://{{ template "presto.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.server.config.http.port }}

{{- if .Values.server.config.https }}
  password-authenticator.properties: |
    password-authenticator.name=v3io
{{- end }}

{{ if .Values.server.log }}
  log.properties: |
{{- range $key, $val := .Values.server.log }}
{{ printf "%s=%s" $key $val | indent 4}}
{{- end }}
{{ end -}}

{{- range $key, $val := .Values.server.config.extra }}
{{ printf "%s: |" $key | indent 2 }}
{{ $val | indent 4 }}
{{- end }}

  health_check.sh: |
    #!/bin/bash
    curl --silent {{ template "presto.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.server.config.http.port }}/v1/node | tr "," "\n" | grep --silent $(hostname -i)

{{- if .Values.server.config.https }}
  create-cert.sh: |
    #!/bin/bash

    set -e

    echo -n "{{ .Values.server.config.https.keystoreBinary }}" | base64 --decode > {{ .Values.server.config.https.keystore }}
{{- end }}

  hive.properties: |
    connector.name=hive-hadoop2
    hive.metastore.uri=thrift://{{ default "hive" .Values.hive.metastore.hostname }}:{{ default 9083 .Values.hive.metastore.port }}
    hive.config.resources=/hadoop/etc/hadoop/core-site.xml,/hadoop/etc/hadoop/hdfs-site.xml

  docker-presto.sh: |
    #!/bin/bash
    cp {{ .Values.server.config.mapPath }}/*.properties $PRESTO_CONF_DIR
    cp {{ .Values.server.config.mapPath }}/*.config $PRESTO_CONF_DIR

    # Hive configuration
    mv $PRESTO_CONF_DIR/hive.properties $PRESTO_CONF_DIR/catalog/hive.properties

    # Hive dependencies
    ln -s /presto/plugin/v3io/v3io-hcfs_2.11.jar /presto/plugin/hive-hadoop2/v3io-hcfs_2.11.jar
    ln -s /presto/plugin/v3io/scala-library-2.11.12.jar /presto/plugin/hive-hadoop2/scala-library-2.11.12.jar

    launcher run

---
{{- end }}
