{{- if gt (int .Values.server.workers) 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "presto.worker" . }}
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: worker
data:
  node.properties: |
{{- if (eq .Values.server.node.properties.worker.override true) }}
{{ printf "#============= Custom node properties (override) ==========" | indent 4 }}
{{- if .Values.server.node.properties.worker.custom }}
{{ .Values.server.node.properties.worker.custom | indent 4 }}
{{- end }}
{{- else }}
    node.environment={{ .Values.server.node.environment }}
    node.data-dir={{ .Values.server.node.dataDir }}
{{- if .Values.server.node.properties.worker.custom }}
{{ printf "#============= Custom node properties ==========" | indent 4 }}
{{ .Values.server.node.properties.worker.custom | indent 4 }}
{{- end }}
{{- end }}

  jvm.config: |
{{- if (eq .Values.server.jvm.properties.worker.override true) }}
{{ printf "#============= Custom jvm properties (override) ==========" | indent 4 }}
{{- if .Values.server.jvm.properties.worker.custom }}
{{ .Values.server.jvm.properties.worker.custom | indent 4 }}
{{- end }}
{{- else }}
    -server
    -Xmx{{ .Values.server.jvm.maxHeapSize }}
    -XX:+{{ .Values.server.jvm.gcMethod.type }}
    -XX:G1HeapRegionSize={{ .Values.server.jvm.gcMethod.g1.heapRegionSize }}
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
{{- if .Values.server.jvm.properties.worker.custom }}
{{ printf "#============= Custom jvm properties ==========" | indent 4 }}
{{ .Values.server.jvm.properties.worker.custom | indent 4 }}
{{- end }}
{{- end }}

  config.properties: |
{{- if (eq .Values.server.config.properties.worker.override true) }}
{{ printf "#============= Custom config properties (override) ==========" | indent 4 }}
{{- if .Values.server.config.properties.worker.custom }}
{{ .Values.server.config.properties.worker.custom | indent 4 }}
{{- println "coordinator=false" }}
{{- end }}
{{- else }}
    coordinator=false
    http-server.http.port={{ .Values.server.config.http.port }}
{{- if .Values.server.config.https }}
    http-server.https.enabled=true
    http-server.https.port={{ .Values.server.config.https.port }}
    http-server.https.keystore.path={{ .Values.server.config.https.keystore }}
    http-server.https.keystore.key={{ .Values.server.config.https.passphrase }}
    http-server.authentication.type=PASSWORD
{{- end }}
    query.max-memory={{ .Values.server.config.query.maxMemory }}
    query.max-memory-per-node={{ .Values.server.config.query.maxMemoryPerNode }}
    discovery.uri=http://{{ template "presto.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.server.config.http.port }}
{{- if .Values.server.config.properties.worker.custom }}
{{ printf "#============= Custom config properties ==========" | indent 4 }}
{{ .Values.server.config.properties.worker.custom | indent 4 }}
{{- end }}
{{- end }}

{{ if .Values.server.config.https }}
  password-authenticator.properties: |
    password-authenticator.name=v3io
{{- end }}

{{ if .Values.server.log }}
  log.properties: |
{{- if (eq .Values.server.log.properties.worker.override true) }}
{{ printf "#============= Custom log properties (override) ==========" | indent 4 }}
{{- if .Values.server.log.properties.worker.custom }}
{{ .Values.server.log.properties.worker.custom | indent 4 }}
{{- end }}
{{- else }}
{{- range $key, $val := .Values.server.log.categories }}
{{ printf "%s=%s" $key $val | indent 4}}
{{- end }}
{{- if .Values.server.log.properties.worker.custom }}
{{ println }}
{{- printf "#============= Custom log properties ==========" | indent 4 }}
{{ .Values.server.log.properties.worker.custom | indent 4 }}
{{- end }}
{{- end }}
{{ end -}}

{{- range $key, $val := .Values.server.config.extra }}
{{ printf "%s: |" $key | indent 2 }}
{{ $val | indent 4 }}
{{- end }}

  health_check.sh: |
    #!/usr/bin/env bash

{{ include "v3io-configs.script.javaHealthCheckTest" . | indent 4 }}

    IP=$(hostname -i)
    echo "IP=$IP"
    CURL_TIMEOUT={{ default 10 .Values.server.config.http.timeout }}
    CURL_CMD="curl --disable --silent --fail --connect-timeout $CURL_TIMEOUT {{ template "presto.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.server.config.http.port }}/v1/node"
    echo "Curl command: $CURL_CMD"
    CURL_OUT=$($CURL_CMD)
    RC=$?
    if [ $RC != 0 ]; then
      echo "command '$CURL_CMD' has failed. RC=$RC. Output: $CURL_OUT"
      exit $RC
    fi

    PARSE_CMD="echo $CURL_OUT | tr ',' '\n' | grep --silent $IP"
    echo "Parse command: $PARSE_CMD"
    PARSE_OUT=$($PARSE_CMD)
    RC=$?
    if [ $RC != 0 ]; then
      echo "command '$PARSE_CMD' has failed. RC=$RC Output: $PARSE_OUT"
      exit $RC
    fi
    RC=$?
    echo "Connectivity check passed. RC=$RC"

    set -e
    CONFIGURED_V3IOD=$(grep "socket.host" $IGZ_DATA_CONFIG_FILE | cut -f2 -d"=")
    if [ "${CONFIGURED_V3IOD}" != "CURRENT_NODE_IP" ]; then
      /var/run/iguazio/daemon_health/healthz --host ${CONFIGURED_V3IOD}
    fi

  daemon-health.sh: |
    #!/usr/bin/env bash

    cp /usr/local/bin/healthz /var/run/iguazio/daemon_health/healthz

{{- if .Values.server.config.https }}
  create-cert.sh: |
    #!/bin/bash

    set -e

    echo -n "{{ .Values.server.config.https.keystoreBinary }}" | base64 --decode > {{ .Values.server.config.https.keystore }}
{{- end }}

  docker-presto.sh: |
    #!/bin/bash

    cp {{ .Values.server.config.mapPath }}/*.properties $PRESTO_CONF_DIR
    cp {{ .Values.server.config.mapPath }}/*.config $PRESTO_CONF_DIR
    cp {{ .Values.server.config.mapPath }}/*.json $PRESTO_CONF_DIR
    cp {{ .Values.server.config.catalogMapPath }}/*.properties $PRESTO_CONF_DIR/catalog

{{- if .Values.hive }}
    # append to Hive configuration
    echo hive.config.resources=${HADOOP_CONF_DIR}/core-site.xml,${HADOOP_CONF_DIR}/hdfs-site.xml >> $PRESTO_CONF_DIR/catalog/hive.properties

    # Hive dependencies
    ln -s ${PRESTO_HOME}/plugin/v3io/v3io-hcfs_${SCALA_MAJOR_VERSION}.jar ${PRESTO_HOME}/plugin/hive-hadoop2/v3io-hcfs_${SCALA_MAJOR_VERSION}.jar
    ln -s ${PRESTO_HOME}/plugin/v3io/scala-library-${SCALA_VERSION}.jar ${PRESTO_HOME}/plugin/hive-hadoop2/scala-library-${SCALA_VERSION}.jar
{{- end }}

    launcher run

---
{{- end }}
