image:
  repository: imakhlin/hive
  tag: 2.3.3-2.9.0-ops
  pullPolicy: IfNotPresent
  command: /etc/config/v3io/v3io-hive.sh

replicas: 1

configPath: /igz/hive/conf-updated

server:
  servicePort: 10000
  containerPort: 10000

ui:
  servicePort: 10002
  containerPort: 10002

metastore:
  servicePort: 9083
  containerPort: 9083

databaseType: postgres

mysql:
  hostname: mysql-hive
  port: 3306
  database: metastore
  username: hive
  password: hive

postgres:
  hostname: postgres-hive
  port: 5432
  database: metastore
  username: hive
  password: hive

config:
  hostname: iguazio-cloud

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

environment:
  template: v3io-configs.deployment.env

volumes:
  volumesTemplate: v3io-configs.deployment.mount
  volumeMountsTemplate: v3io-configs.deployment.volumeMounts

global:
  v3io:
    configMountPath: /etc/config/v3io
    lookupService:
      name: v3iod-locator

v3io: {}
