apiVersion: v1
name: mlrun
version: 0.2.1
description: Machine Learning automation and tracking
type: application
sources:
  - https://github.com/mlrun/mlrun
maintainers:
  - name: hedingber
    email: hedii@iguazio.com
icon: https://www.iguazio.com/wp-content/uploads/2019/10/Iguazio-Logo.png
appVersion: 0.4.3
